import type { ItemDef } from "../engine/types";

export const ITEMS: Record<string, ItemDef> = {
  // --- Potions ---
  health_potion: {
    id: "health_potion",
    name: "Health Potion",
    symbol: "!",
    color: "#ef4444",
    type: "potion",
    description: "Restores 20 health points.",
    effect: { stat: "health", amount: 20 },
    value: 25,
    stackable: true,
  },
  greater_health_potion: {
    id: "greater_health_potion",
    name: "Greater Health Potion",
    symbol: "!",
    color: "#dc2626",
    type: "potion",
    description: "Restores 50 health points.",
    effect: { stat: "health", amount: 50 },
    value: 60,
    stackable: true,
  },
  elixir_of_vigor: {
    id: "elixir_of_vigor",
    name: "Elixir of Vigor",
    symbol: "!",
    color: "#f59e0b",
    type: "potion",
    description: "Permanently increases max health by 10.",
    effect: { stat: "maxHealth", amount: 10 },
    value: 200,
    stackable: false,
  },

  // --- Food ---
  bread: {
    id: "bread",
    name: "Bread",
    symbol: "o",
    color: "#d4a574",
    type: "food",
    description: "Restores 8 health. Simple but filling.",
    effect: { stat: "health", amount: 8 },
    value: 5,
    stackable: true,
  },
  mushroom_stew: {
    id: "mushroom_stew",
    name: "Mushroom Stew",
    symbol: "o",
    color: "#a3e635",
    type: "food",
    description: "Restores 15 health. Earthy and warm.",
    effect: { stat: "health", amount: 15 },
    value: 12,
    stackable: true,
  },

  // --- Weapons ---
  rusty_dagger: {
    id: "rusty_dagger",
    name: "Rusty Dagger",
    symbol: "†",
    color: "#78716c",
    type: "weapon",
    description: "A pitted, dull blade. +2 Attack.",
    effect: { stat: "attack", amount: 2 },
    value: 10,
    stackable: false,
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    symbol: "†",
    color: "#94a3b8",
    type: "weapon",
    description: "A sturdy iron blade. +5 Attack.",
    effect: { stat: "attack", amount: 5 },
    value: 50,
    stackable: false,
  },
  silver_rapier: {
    id: "silver_rapier",
    name: "Silver Rapier",
    symbol: "†",
    color: "#e2e8f0",
    type: "weapon",
    description: "Elegant and precise. +8 Attack. Effective against undead.",
    effect: { stat: "attack", amount: 8 },
    value: 120,
    stackable: false,
  },
  shadow_blade: {
    id: "shadow_blade",
    name: "Shadow Blade",
    symbol: "†",
    color: "#7c3aed",
    type: "weapon",
    description: "Forged in darkness. +12 Attack. Whispers when drawn.",
    effect: { stat: "attack", amount: 12 },
    value: 300,
    stackable: false,
  },

  // --- Armor ---
  leather_vest: {
    id: "leather_vest",
    name: "Leather Vest",
    symbol: "◉",
    color: "#92400e",
    type: "armor",
    description: "Light protection. +2 Defense.",
    effect: { stat: "defense", amount: 2 },
    value: 20,
    stackable: false,
  },
  iron_shield: {
    id: "iron_shield",
    name: "Iron Shield",
    symbol: "◉",
    color: "#94a3b8",
    type: "armor",
    description: "A battered iron shield. +4 Defense.",
    effect: { stat: "defense", amount: 4 },
    value: 40,
    stackable: false,
  },
  knight_armor: {
    id: "knight_armor",
    name: "Knight's Armor",
    symbol: "◉",
    color: "#cbd5e1",
    type: "armor",
    description: "Heavy plate armor. +7 Defense.",
    effect: { stat: "defense", amount: 7 },
    value: 150,
    stackable: false,
  },

  // --- Scrolls ---
  scroll_fireball: {
    id: "scroll_fireball",
    name: "Scroll of Fireball",
    symbol: "?",
    color: "#f97316",
    type: "scroll",
    description: "Deals 15 fire damage to a target.",
    effect: { stat: "health", amount: -15 },
    value: 75,
    stackable: true,
  },
  scroll_light: {
    id: "scroll_light",
    name: "Scroll of Light",
    symbol: "?",
    color: "#fde68a",
    type: "scroll",
    description: "Illuminates a wide area temporarily.",
    value: 30,
    stackable: true,
  },

  // --- Key Items ---
  torch: {
    id: "torch",
    name: "Torch",
    symbol: "¡",
    color: "#f59e0b",
    type: "key",
    description: "Illuminates dark areas.",
    value: 5,
    stackable: true,
  },
  crypt_key: {
    id: "crypt_key",
    name: "Crypt Key",
    symbol: "ƒ",
    color: "#a78bfa",
    type: "key",
    description: "An ancient key. Engraved with symbols of mourning.",
    value: 0,
    stackable: false,
  },
  locket: {
    id: "locket",
    name: "Tarnished Locket",
    symbol: "♥",
    color: "#f9a8d4",
    type: "key",
    description: "Contains a faded portrait. Someone may recognize it.",
    value: 0,
    stackable: false,
  },
  old_journal: {
    id: "old_journal",
    name: "Old Journal",
    symbol: "≡",
    color: "#d4a574",
    type: "key",
    description: "Water-stained pages. The last entry reads: 'The music stopped.'",
    value: 0,
    stackable: false,
  },

  // --- Treasure ---
  rat_tail: {
    id: "rat_tail",
    name: "Rat Tail",
    symbol: "~",
    color: "#a1a1aa",
    type: "treasure",
    description: "Proof of a slain rat. The guard might be interested.",
    value: 10,
    stackable: true,
  },
  gold_pile: {
    id: "gold_pile",
    name: "Gold Pile",
    symbol: "$",
    color: "#fbbf24",
    type: "treasure",
    description: "A small pile of gold coins.",
    value: 50,
    stackable: true,
  },
  sapphire: {
    id: "sapphire",
    name: "Sapphire",
    symbol: "◆",
    color: "#3b82f6",
    type: "treasure",
    description: "A deep blue gemstone. Cold to the touch.",
    value: 150,
    stackable: false,
  },
  bone_charm: {
    id: "bone_charm",
    name: "Bone Charm",
    symbol: "∞",
    color: "#e2e8f0",
    type: "treasure",
    description: "Carved from something that was once alive. Hums faintly.",
    value: 80,
    stackable: false,
  },
};
