import type { ItemDef } from "../engine/types";

export const ITEMS: Record<string, ItemDef> = {
  health_potion: {
    id: "health_potion",
    name: "Health Potion",
    symbol: "!",
    color: "#ef4444",
    type: "potion",
    description: "Restores 20 health points.",
    effect: { stat: "health", amount: 20 },
    value: 25,
    stackable: true,
  },
  iron_sword: {
    id: "iron_sword",
    name: "Iron Sword",
    symbol: "†",
    color: "#94a3b8",
    type: "weapon",
    description: "A sturdy iron blade. +5 Attack.",
    effect: { stat: "attack", amount: 5 },
    value: 50,
    stackable: false,
  },
  iron_shield: {
    id: "iron_shield",
    name: "Iron Shield",
    symbol: "◉",
    color: "#94a3b8",
    type: "armor",
    description: "A battered iron shield. +3 Defense.",
    effect: { stat: "defense", amount: 3 },
    value: 40,
    stackable: false,
  },
  torch: {
    id: "torch",
    name: "Torch",
    symbol: "¡",
    color: "#f59e0b",
    type: "key",
    description: "Illuminates dark areas.",
    value: 5,
    stackable: true,
  },
  rat_tail: {
    id: "rat_tail",
    name: "Rat Tail",
    symbol: "~",
    color: "#a1a1aa",
    type: "treasure",
    description: "Proof of a slain rat. The guard might be interested.",
    value: 10,
    stackable: true,
  },
  gold_pile: {
    id: "gold_pile",
    name: "Gold Pile",
    symbol: "$",
    color: "#fbbf24",
    type: "treasure",
    description: "A small pile of gold coins.",
    value: 50,
    stackable: true,
  },
  scroll_fireball: {
    id: "scroll_fireball",
    name: "Scroll of Fireball",
    symbol: "?",
    color: "#f97316",
    type: "scroll",
    description: "Deals 15 fire damage to a target.",
    effect: { stat: "health", amount: -15 },
    value: 75,
    stackable: true,
  },
  bread: {
    id: "bread",
    name: "Bread",
    symbol: "o",
    color: "#d4a574",
    type: "food",
    description: "Restores 8 health. Simple but filling.",
    effect: { stat: "health", amount: 8 },
    value: 5,
    stackable: true,
  },
};
